language: java
sudo: false
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
os:
  - windows
script:
  - nvm clean verify
  - ./scripts/run-tests.sh